# Generated by Django 3.2.5 on 2022-08-13 12:52

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
